Repository input-output-hk/hermes, pull requests merged in 2024-03, with the labels that each got.

#71 docs: Adds notes on Hermes packaging requirements
  .config/dictionaries/project.dic
  .markdownlint-cli2.jsonc
  .vscode/extensions.json
  cspell.json
  docs/Earthfile
  docs/src/architecture/08_concepts/.pages
  docs/src/architecture/08_concepts/hermes_packaging_requirements/.pages
  docs/src/architecture/08_concepts/hermes_packaging_requirements/app_data.md
  docs/src/architecture/08_concepts/hermes_packaging_requirements/app_loading.md
  docs/src/architecture/08_concepts/hermes_packaging_requirements/app_metadata.md
  docs/src/architecture/08_concepts/hermes_packaging_requirements/app_package.md
  docs/src/architecture/08_concepts/hermes_packaging_requirements/app_signatures.md
  docs/src/architecture/08_concepts/hermes_packaging_requirements/app_srv_www.md
  docs/src/architecture/08_concepts/hermes_packaging_requirements/images/app_loading_overview.d2
  docs/src/architecture/08_concepts/hermes_packaging_requirements/images/application_metadata.d2
  docs/src/architecture/08_concepts/hermes_packaging_requirements/images/application_package_hierarchy.d2
  docs/src/architecture/08_concepts/hermes_packaging_requirements/images/application_root.dot
  docs/src/architecture/08_concepts/hermes_packaging_requirements/images/hdf5_file_structure.dot
  docs/src/architecture/08_concepts/hermes_packaging_requirements/images/hermes_app_metadata.excalidraw
  docs/src/architecture/08_concepts/hermes_packaging_requirements/images/hermes_app_object_metadata.excalidraw
  docs/src/architecture/08_concepts/hermes_packaging_requirements/images/wasm_component_module.d2
  docs/src/architecture/08_concepts/hermes_packaging_requirements/images/wasm_module_metadata.dot
  docs/src/architecture/08_concepts/hermes_packaging_requirements/overview.md
  docs/src/architecture/08_concepts/hermes_packaging_requirements/wasm_modules.md
  docs/src/architecture/08_concepts/hermes_runtime_engine/h_app_struct.md
  hermes/Earthfile
  hermes/schemas/example/hermes_app_manifest.json
  hermes/schemas/example/hermes_app_metadata.json
  hermes/schemas/example/hermes_module_manifest.json
  hermes/schemas/example/hermes_module_metadata.json
  hermes/schemas/hermes_app_manifest.schema.json
  hermes/schemas/hermes_app_metadata.schema.json
  hermes/schemas/hermes_module_manifest.schema.json
  hermes/schemas/hermes_module_metadata.schema.json
Labels: documentation, draft

#174 docs(hermes): Document how the follower runtime extension manages instances
  .config/dictionaries/project.dic
  docs/Earthfile
  docs/src/api/index.md
  docs/src/architecture/05_building_block_view/hermes_core.md
  docs/src/architecture/05_building_block_view/images/hermes_core.svg
  docs/src/architecture/08_concepts/cardano_chain_follower/.pages
  docs/src/architecture/08_concepts/cardano_chain_follower/follower_instances.md
  docs/src/architecture/08_concepts/cardano_chain_follower/images/chain_follower_overview.excalidraw
  docs/src/architecture/08_concepts/cardano_chain_follower/images/chain_follower_overview.svg
  docs/src/architecture/08_concepts/cardano_chain_follower/images/simplified-get-update-flow.svg
  docs/src/architecture/08_concepts/cardano_chain_follower/images/simplified-reader-block-range-flow.svg
  docs/src/architecture/08_concepts/cardano_chain_follower/images/simplified-reader-single-block-flow.svg
  docs/src/architecture/08_concepts/cardano_chain_follower/overview.md
  docs/src/architecture/08_concepts/hermes_runtime_engine/h_app_exec.md
  docs/src/architecture/08_concepts/hermes_runtime_engine/h_events_queue.md
  docs/src/architecture/08_concepts/hermes_runtime_engine/images/event_queue.svg
  docs/src/architecture/08_concepts/hermes_runtime_engine/images/hermes_application.svg
Labels: documentation

#169 docs: HRE implementation notes
  docs/Earthfile
  docs/src/architecture/04_solution_strategy.md
  docs/src/architecture/05_building_block_view/.pages
  docs/src/architecture/05_building_block_view/hermes_core.md
  docs/src/architecture/05_building_block_view/hermes_engine.md
  docs/src/architecture/05_building_block_view/images/hermes_core.svg
  docs/src/architecture/05_building_block_view/images/hermes_engine.excalidraw
  docs/src/architecture/05_building_block_view/images/hermes_engine.svg
  docs/src/architecture/08_concepts/hermes_runtime_engine/.pages
  docs/src/architecture/08_concepts/hermes_runtime_engine/h_app_exec.md
  docs/src/architecture/08_concepts/hermes_runtime_engine/h_app_struct.md
  docs/src/architecture/08_concepts/hermes_runtime_engine/h_events_queue.md
  docs/src/architecture/08_concepts/hermes_runtime_engine/hre_init_setup.md
  docs/src/architecture/08_concepts/hermes_runtime_engine/hre_interface.md
  docs/src/architecture/08_concepts/hermes_runtime_engine/hre_state.md
  docs/src/architecture/08_concepts/hermes_runtime_engine/hre_structure.md
  docs/src/architecture/08_concepts/hermes_runtime_engine/wasm_parallel.md
Labels: documentation, review me

#142 feat(rust): Time Module Implementation
  .config/dictionaries/project.dic
  hermes/Cargo.toml
  hermes/bin/Cargo.toml
  hermes/bin/src/runtime_extensions/hermes/cron/mod.rs
  hermes/bin/src/runtime_extensions/hermes/localtime/host.rs
  hermes/bin/src/runtime_extensions/hermes/localtime/mod.rs
  hermes/bin/src/runtime_extensions/wasi/clocks/mod.rs
  hermes/bin/src/runtime_extensions/wasi/clocks/monotonic/host.rs
  hermes/bin/src/runtime_extensions/wasi/clocks/state.rs
  hermes/bin/src/runtime_extensions/wasi/clocks/wall/host.rs
Labels: enhancement

#182 fix(cardano-chain-follower): Refactor cardano-chain-follower to fix client concurrency bug
  docs/src/architecture/08_concepts/cardano_chain_follower/overview.md
  hermes/crates/cardano-chain-follower/examples/concurrent_reads.rs
  hermes/crates/cardano-chain-follower/examples/read_block.rs
  hermes/crates/cardano-chain-follower/examples/read_block_mithril.rs
  hermes/crates/cardano-chain-follower/examples/read_block_range.rs
  hermes/crates/cardano-chain-follower/examples/read_block_range_mithril.rs
  hermes/crates/cardano-chain-follower/examples/set_read_pointer.rs
  hermes/crates/cardano-chain-follower/src/follow.rs
  hermes/crates/cardano-chain-follower/src/lib.rs
  hermes/crates/cardano-chain-follower/src/mithril_snapshot.rs
Labels: review me

#127 feat(api): Implement Ed25519-BIP32
  .config/dictionaries/project.dic
  hermes/Cargo.toml
  hermes/Earthfile
  hermes/bin/Cargo.toml
  hermes/bin/src/runtime_extensions/hermes/crypto/bip32_ed25519.rs
  hermes/bin/src/runtime_extensions/hermes/crypto/bip39.rs
  hermes/bin/src/runtime_extensions/hermes/crypto/host.rs
  hermes/bin/src/runtime_extensions/hermes/crypto/mod.rs
  hermes/bin/src/runtime_extensions/hermes/crypto/state.rs
  hermes/deny.toml
  wasm/wasi-hermes-component-adapter/Earthfile
  wasm/wasi-hermes-component-adapter/deny.toml
  wasm/wasi/wit/deps/hermes-crypto/api.wit
Labels: enhancement, review me

#184 fix(cardano-chain-follower): set_read_pointer now returns None when the requested point is not found
  hermes/crates/cardano-chain-follower/src/follow.rs
Labels: review me

#185 chore(cardano-chain-follower): Add ways to get the raw bytes for MultiEraBlockData
  hermes/crates/cardano-chain-follower/src/lib.rs
Labels: review me

#186 feat: logger
  hermes/Cargo.toml
  hermes/bin/Cargo.toml
  hermes/bin/build.rs
  hermes/bin/src/lib.rs
  hermes/bin/src/logger.rs
  hermes/bin/src/main.rs
  hermes/bin/src/runtime_extensions/hermes/logging/host.rs
  hermes/bin/src/runtime_extensions/hermes/logging/log_msg.rs
  hermes/bin/src/runtime_extensions/hermes/logging/mod.rs
  hermes/bin/src/runtime_extensions/mod.rs
  hermes/bin/src/runtime_extensions/wasi/clocks/state.rs
  wasm/wasi/wit/deps/hermes-logging/api.wit
Labels: enhancement, review me

#189 fix: Patch pallas lib, use catalyst-pallas repo
  hermes/Cargo.toml
  hermes/Earthfile
  hermes/crates/cbork/Earthfile
  hermes/crates/cbork/deny.toml
  hermes/deny.toml
  wasm/wasi-hermes-component-adapter/Earthfile
Labels: review me
