Repository input-output-hk/hermes, pull requests merged in 2024-08, with the labels that each got.

#315 feat: Add more tests for module packaging module
  hermes/bin/src/hdf5/resources/builder.rs
  hermes/bin/src/hdf5/resources/fs.rs
  hermes/bin/src/hdf5/resources/mod.rs
  hermes/bin/src/packaging/app/manifest.rs
  hermes/bin/src/packaging/app/mod.rs
  hermes/bin/src/packaging/app/module_info.rs
  hermes/bin/src/packaging/app/tests.rs
  hermes/bin/src/packaging/module/config_info.rs
  hermes/bin/src/packaging/module/manifest.rs
  hermes/bin/src/packaging/module/mod.rs
  hermes/bin/src/packaging/module/tests.rs
Labels: review me

#314 feat: x509 metadata decode
  .config/dictionaries/project.dic
  hermes/Cargo.toml
  hermes/crates/cardano-chain-follower/Cargo.toml
  hermes/crates/cardano-chain-follower/src/lib.rs
  hermes/crates/cardano-chain-follower/src/metadata/mod.rs
  hermes/crates/cardano-chain-follower/src/metadata/x509/mod.rs
  hermes/crates/cardano-chain-follower/src/metadata/x509/rbac/certs.rs
  hermes/crates/cardano-chain-follower/src/metadata/x509/rbac/mod.rs
  hermes/crates/cardano-chain-follower/src/metadata/x509/rbac/pub_key.rs
  hermes/crates/cardano-chain-follower/src/metadata/x509/rbac/role_data.rs
Labels: enhancement

#317 feat: Add more tests for application packaging module
  hermes/bin/src/hdf5/dir.rs
  hermes/bin/src/hdf5/path.rs
  hermes/bin/src/packaging/app/mod.rs
  hermes/bin/src/packaging/app/module_info.rs
  hermes/bin/src/packaging/app/tests.rs
  hermes/bin/src/packaging/module/tests.rs
Labels: review me

#322 refactor: Hermes Reactor
  .config/dictionaries/project.dic
  hermes/bin/src/app.rs
  hermes/bin/src/cli/app/package.rs
  hermes/bin/src/cli/app/sign.rs
  hermes/bin/src/cli/module/package.rs
  hermes/bin/src/cli/module/sign.rs
  hermes/bin/src/cli/run.rs
  hermes/bin/src/event/mod.rs
  hermes/bin/src/event/queue.rs
  hermes/bin/src/packaging/app/app_builder.rs
  hermes/bin/src/packaging/app/mod.rs
  hermes/bin/src/reactor.rs
  hermes/bin/src/runtime_context.rs
  hermes/bin/src/runtime_extensions/app_config.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/chain_follower_task.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/mod.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/tokio_runtime_task.rs
  hermes/bin/src/runtime_extensions/hermes/cron/mod.rs
  hermes/bin/src/runtime_extensions/hermes/cron/queue.rs
  hermes/bin/src/runtime_extensions/hermes/cron/state.rs
  hermes/bin/src/runtime_extensions/hermes/crypto/state.rs
  hermes/bin/src/runtime_extensions/hermes/http_gateway/mod.rs
  hermes/bin/src/runtime_extensions/hermes/http_gateway/routing.rs
  hermes/bin/src/runtime_extensions/hermes/init/mod.rs
  hermes/bin/src/runtime_extensions/hermes/integration_test/event.rs
  hermes/bin/src/runtime_extensions/hermes/ipfs/state/api.rs
  hermes/bin/src/runtime_extensions/hermes/ipfs/state/mod.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/connection/core.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/core.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/state.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/statement/core.rs
  hermes/bin/src/wasm/module.rs
Labels: review me

#321 feat: basic WASI filesystem functions
  .config/dictionaries/project.dic
  hermes/.gitignore
  hermes/Earthfile
  hermes/bin/src/hdf5/file.rs
  hermes/bin/src/runtime_extensions/bindings.rs
  hermes/bin/src/runtime_extensions/wasi/cli/host.rs
  hermes/bin/src/runtime_extensions/wasi/context.rs
  hermes/bin/src/runtime_extensions/wasi/descriptors.rs
  hermes/bin/src/runtime_extensions/wasi/filesystem/host.rs
  hermes/bin/src/runtime_extensions/wasi/filesystem/mod.rs
  hermes/bin/src/runtime_extensions/wasi/io/streams/host.rs
  hermes/bin/src/runtime_extensions/wasi/mod.rs
  hermes/bin/src/runtime_extensions/wasi/state.rs
  hermes/bin/src/vfs/mod.rs
  wasm/integration-test/wasi-filesystem/.gitignore
  wasm/integration-test/wasi-filesystem/Cargo.toml
  wasm/integration-test/wasi-filesystem/Earthfile
  wasm/integration-test/wasi-filesystem/src/lib.rs
  wasm/integration-test/wasi-filesystem/src/tests.rs
Labels: review me

#327 feat: extracting transaction witness
  .config/dictionaries/project.dic
  hermes/crates/cardano-chain-follower/src/lib.rs
  hermes/crates/cardano-chain-follower/src/multi_era_block_data.rs
  hermes/crates/cardano-chain-follower/src/utils.rs
  hermes/crates/cardano-chain-follower/src/witness.rs
  hermes/crates/cardano-chain-follower/test_data/babbage.block
Labels: enhancement, review me

#325 test(chain-follower): Add integration test to download Mithil Snapshot and validate it
  hermes/Earthfile
  hermes/crates/cardano-chain-follower/examples/follow_chains.rs
  hermes/crates/cardano-chain-follower/src/chain_sync.rs
  hermes/crates/cardano-chain-follower/src/mithril_snapshot_config.rs
  hermes/crates/cardano-chain-follower/src/mithril_snapshot_sync.rs
  hermes/crates/cardano-chain-follower/src/multi_era_block_data.rs
Labels: review me

#316 feat: Hermes IPFS loading VFS
  .config/dictionaries/project.dic
  hermes/Cargo.toml
  hermes/bin/src/cli/run.rs
  hermes/bin/src/ipfs/api.rs
  hermes/bin/src/ipfs/mod.rs
  hermes/bin/src/ipfs/task.rs
  hermes/bin/src/lib.rs
  hermes/bin/src/main.rs
  hermes/bin/src/runtime_extensions/hermes/ipfs/host.rs
  hermes/bin/src/runtime_extensions/hermes/ipfs/mod.rs
  hermes/bin/src/vfs/bootstrap.rs
  hermes/bin/src/vfs/ipfs.rs
  hermes/bin/src/vfs/mod.rs
  hermes/bin/tests/wasm-integration/main.rs
  hermes/crates/hermes-ipfs/Cargo.toml
  hermes/crates/hermes-ipfs/examples/hermes-ipfs-cli.rs
  hermes/crates/hermes-ipfs/src/lib.rs
  wasm/wasi/wit/deps/hermes-ipfs/api.wit
Labels: enhancement, review me

#345 fix: chain follower `get_block`
  hermes/crates/cardano-chain-follower/src/follow.rs
Labels: bug

#344 fix: Re-enable default transport config for IPFS
  hermes/Cargo.toml
  hermes/bin/src/ipfs/mod.rs
  hermes/crates/hermes-ipfs/examples/hermes-ipfs-cli.rs
  hermes/crates/hermes-ipfs/src/lib.rs
Labels: review me

#340 feat: Generalised resource manager
  hermes/bin/src/runtime_extensions/bindings.rs
  hermes/bin/src/runtime_extensions/hermes/crypto/host.rs
  hermes/bin/src/runtime_extensions/hermes/crypto/mod.rs
  hermes/bin/src/runtime_extensions/hermes/crypto/state.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/connection/host.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/host.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/mod.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/state.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/statement/host.rs
  hermes/bin/src/runtime_extensions/mod.rs
  hermes/bin/src/runtime_extensions/resource_manager.rs
  hermes/bin/src/runtime_extensions/wasi/cli/host.rs
  hermes/bin/src/runtime_extensions/wasi/context.rs
  hermes/bin/src/runtime_extensions/wasi/descriptors.rs
  hermes/bin/src/runtime_extensions/wasi/filesystem/host.rs
  hermes/bin/src/runtime_extensions/wasi/filesystem/mod.rs
  hermes/bin/src/runtime_extensions/wasi/filesystem/state.rs
  hermes/bin/src/runtime_extensions/wasi/io/streams/host.rs
  hermes/bin/src/runtime_extensions/wasi/io/streams/mod.rs
  hermes/bin/src/runtime_extensions/wasi/io/streams/state.rs
  hermes/bin/src/runtime_extensions/wasi/mod.rs
  hermes/bin/src/runtime_extensions/wasi/state.rs
Labels: review me

#341 test(chain-follower): Add unit tests to metadata decoding on CIP36
  hermes/crates/cardano-chain-follower/src/metadata/cip36.rs
  hermes/crates/cardano-chain-follower/src/multi_era_block_data.rs
Labels: review me
