Repository input-output-hk/hermes, pull requests merged in 2024-02, with the labels that each got.

#73 feat: Wasm module implementation
  .config/dictionaries/project.dic
  hermes/Cargo.toml
  hermes/Earthfile
  hermes/bin/Cargo.toml
  hermes/bin/src/lib.rs
  hermes/bin/src/main.rs
  hermes/bin/src/wasm/context.rs
  hermes/bin/src/wasm/engine.rs
  hermes/bin/src/wasm/mod.rs
  hermes/bin/src/wasm/module.rs
  hermes/crates/cardano-chain-follower/Cargo.toml
  hermes/deny.toml
  wasm/wasi-hermes-component-adapter/Earthfile
  wasm/wasi-hermes-component-adapter/deny.toml
Labels: review me

#115 chore(cardano-chain-follower): Merge Reader functions with the Follower
  hermes/crates/cardano-chain-follower/examples/read_block.rs
  hermes/crates/cardano-chain-follower/examples/read_block_mithril.rs
  hermes/crates/cardano-chain-follower/examples/read_block_range.rs
  hermes/crates/cardano-chain-follower/examples/read_block_range_mithril.rs
  hermes/crates/cardano-chain-follower/src/follow.rs
  hermes/crates/cardano-chain-follower/src/lib.rs
  hermes/crates/cardano-chain-follower/src/read.rs
Labels: review me

#120 feat(api): Generate a blake2b hash of a given binary buffer.
  .config/dictionaries/project.dic
  hermes/Cargo.toml
  hermes/bin/Cargo.toml
  hermes/bin/src/runtime_extensions/hermes/hash/blake2b.rs
  hermes/bin/src/runtime_extensions/hermes/hash/host.rs
  hermes/bin/src/runtime_extensions/hermes/hash/mod.rs
  wasm/wasi/wit/deps/hermes-hash/api.wit
Labels: enhancement

#124 feat(Rust API): Implement Rust Cron Module
  .config/dictionaries/project.dic
  hermes/Cargo.toml
  hermes/bin/Cargo.toml
  hermes/bin/src/runtime_extensions/hermes/cron/host.rs
  hermes/bin/src/runtime_extensions/hermes/cron/mod.rs
  hermes/bin/src/runtime_extensions/hermes/mod.rs
Labels: enhancement, review me

#138 chore: repo cleanups
  .gitignore
  .vscode/extensions.json
Labels: enhancement

#118 feat(wasm): C stub
  .config/dictionaries/project.dic
  wasm/event-stubs/Earthfile
  wasm/event-stubs/my-component.c
Labels: review me

#136 feat: `bindings-expand` Earthly target
  hermes/Earthfile
  hermes/bin/src/runtime_extensions/bindings.rs
  hermes/example_code/ext.rs
  wasm/event-stubs/Earthfile
  wasm/wasi-hermes-component-adapter/Earthfile
Labels: review me

#157 feat: follower connection
  hermes/crates/cardano-chain-follower/src/follow.rs
Labels: review me

#109 feat: `wasm::Module` benchmark
  cspell.json
  hermes/Cargo.toml
  hermes/Earthfile
  hermes/README.md
  hermes/bin/Cargo.toml
  hermes/bin/benches/module.rs
  hermes/bin/src/lib.rs
  hermes/bin/src/main.rs
  hermes/bin/src/wasm/module.rs
  hermes/deny.toml
  wasm/c/Earthfile
  wasm/c/my-component.c
  wasm/wasi-hermes-component-adapter/Earthfile
  wasm/wasi-hermes-component-adapter/deny.toml
Labels: review me
