Repository input-output-hk/hermes, pull requests merged in 2025-09, with the labels that each got.

#518 feat(hermes): parallel sql processing
  .config/dictionaries/project.dic
  hermes/bin/src/runtime_extensions/hermes/sqlite/connection/core.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/core.rs
  hermes/bin/tests/integration/components/sleep_component/src/lib.rs
  hermes/bin/tests/integration/tests/serial/parallel_module_execution.rs
Labels: review me, rust, squad: hermetics

#527 feat(hermes): dynamic init constuctor fix.
  .config/dictionaries/project.dic
  .github/CODEOWNERS
  .gitignore
  Earthfile
  docs/Earthfile
  hermes/.config/nextest.toml
  hermes/Earthfile
  hermes/apps/athena/modules/.gitignore
  hermes/apps/athena/modules/Earthfile
  hermes/bin/src/app.rs
  hermes/bin/src/cli/playground.rs
  hermes/bin/src/packaging/app/app_builder.rs
  hermes/bin/src/reactor.rs
  hermes/bin/src/runtime_extensions/hermes/cron/queue.rs
  hermes/bin/src/runtime_extensions/hermes/logging/mod.rs
  hermes/bin/src/runtime_extensions/init/executor.rs
  hermes/bin/src/runtime_extensions/init/trait_app.rs
  hermes/bin/src/runtime_extensions/init/trait_event.rs
  hermes/bin/src/runtime_extensions/init/trait_module.rs
  hermes/bin/src/runtime_extensions/init/trait_runtime.rs
  hermes/rust-toolchain.toml
  justfile
  wasm/examples/c/cardano_age/Earthfile
  wasm/examples/c/next_century/Earthfile
  wasm/examples/rust/cardano/Earthfile
  wasm/examples/rust/cardano_age/Earthfile
  wasm/examples/rust/next_century/Earthfile
  wasm/integration-test/cardano/Earthfile
  wasm/integration-test/clocks/Earthfile
  wasm/integration-test/cron/Earthfile
  wasm/integration-test/crypto/Earthfile
  wasm/integration-test/golang/Earthfile
  wasm/integration-test/hashing/Earthfile
  wasm/integration-test/http_reply/Earthfile
  wasm/integration-test/ipfs/Earthfile
  wasm/integration-test/localtime/Earthfile
  wasm/integration-test/logger/Earthfile
  wasm/integration-test/smoke-test/Earthfile
  wasm/integration-test/sqlite/Earthfile
  wasm/integration-test/wasi-filesystem/Earthfile
  wasm/stub-module/Earthfile
  wasm/wasi/Earthfile
Labels: review me

#529 chore(hermes): Clean up cspell dictionary
  .config/dictionaries/project.dic
Labels: squad: hermetics

#530 feat(hermes): web integration via static assets
  .config/dictionaries/project.dic
  Earthfile
  hermes/apps/athena/manifest_app.json
  hermes/apps/athena/modules/Earthfile
  hermes/apps/athena/modules/http-proxy/lib/config.json
  hermes/apps/athena/modules/http-proxy/lib/manifest.json
  hermes/apps/athena/modules/http-proxy/lib/manifest_module.json
  hermes/apps/athena/modules/http-proxy/lib/version.json
  hermes/bin/src/logger.rs
  hermes/bin/src/runtime_extensions/hermes/http_gateway/routing.rs
  justfile
  wasm/examples/c/next_century/Earthfile
  wasm/integration-test/golang/Earthfile
  wasm/wasi/Earthfile
Labels: fyi: hermetics

#541 feat(athena): Add rbac-registration module to Athena
  .config/dictionaries/project.dic
  .github/workflows/semantic_pull_request.yml
  hermes/apps/athena/manifest_app.json
  hermes/apps/athena/modules/rbac-registration/Cargo.toml
  hermes/apps/athena/modules/rbac-registration/Earthfile
  hermes/apps/athena/modules/rbac-registration/blueprint.cue
  hermes/apps/athena/modules/rbac-registration/lib/config.json
  hermes/apps/athena/modules/rbac-registration/lib/config.schema.json
  hermes/apps/athena/modules/rbac-registration/lib/manifest_module.json
  hermes/apps/athena/modules/rbac-registration/lib/metadata.json
  hermes/apps/athena/modules/rbac-registration/lib/settings.schema.json
  hermes/apps/athena/modules/rbac-registration/src/database/create.rs
  hermes/apps/athena/modules/rbac-registration/src/database/data/mod.rs
  hermes/apps/athena/modules/rbac-registration/src/database/data/rbac_db.rs
  hermes/apps/athena/modules/rbac-registration/src/database/data/rbac_stake_db.rs
  hermes/apps/athena/modules/rbac-registration/src/database/insert.rs
  hermes/apps/athena/modules/rbac-registration/src/database/mod.rs
  hermes/apps/athena/modules/rbac-registration/src/lib.rs
  hermes/apps/athena/modules/rbac-registration/src/utils/cardano/block.rs
  hermes/apps/athena/modules/rbac-registration/src/utils/cardano/mod.rs
  hermes/apps/athena/modules/rbac-registration/src/utils/log.rs
  hermes/apps/athena/modules/rbac-registration/src/utils/mod.rs
  hermes/apps/athena/modules/rbac-registration/src/utils/value.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/host.rs
  justfile
  wasm/wasi/wit/deps/hermes-cardano/api.wit
Labels: review me, squad: hermetics

#535 fix(hermes): thread_local sqlite resource management
  hermes/apps/athena/modules/rbac-registration/src/lib.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/connection/core.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/connection/host.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/host.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/kernel.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/mod.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/state.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/state/connection.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/state/manager.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/state/mod.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/state/resource_manager.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/state/statement.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/statement/core.rs
  hermes/bin/src/runtime_extensions/hermes/sqlite/statement/host.rs
  hermes/bin/src/runtime_extensions/init/trait_app.rs
  hermes/bin/src/runtime_extensions/init/trait_event.rs
  hermes/bin/src/runtime_extensions/init/trait_module.rs
  hermes/bin/tests/integration/components/sleep_component/src/lib.rs
  hermes/bin/tests/integration/tests/serial/parallel_module_execution.rs
  wasm/integration-test/sqlite/src/test.rs
  wasm/wasi/wit/deps/hermes-sqlite/api.wit
Labels: review me, squad: hermetics

#550 fix(athena): Move HTTP proxy to dedicated module with self-contained build configuration
  hermes/apps/athena/manifest_app.json
  hermes/apps/athena/modules/Earthfile
  hermes/apps/athena/modules/http-proxy/Earthfile
  hermes/apps/athena/modules/http-proxy/lib/version.json
  hermes/apps/athena/modules/http-proxy/src/lib.rs
  hermes/apps/athena/modules/http-proxy/src/stub.rs
  justfile
Labels: rr: hermetics

#552 feat(athena): Create `rbac-registration` module
  hermes/apps/athena/manifest_app.json
  hermes/apps/athena/modules/rbac-registration/Cargo.toml
  hermes/apps/athena/modules/rbac-registration/Earthfile
  hermes/apps/athena/modules/rbac-registration/blueprint.cue
  hermes/apps/athena/modules/rbac-registration/lib/config.json
  hermes/apps/athena/modules/rbac-registration/lib/config.schema.json
  hermes/apps/athena/modules/rbac-registration/lib/manifest_module.json
  hermes/apps/athena/modules/rbac-registration/lib/metadata.json
  hermes/apps/athena/modules/rbac-registration/lib/settings.schema.json
  hermes/apps/athena/modules/rbac-registration/src/database/mod.rs
  hermes/apps/athena/modules/rbac-registration/src/database/operation.rs
  hermes/apps/athena/modules/rbac-registration/src/database/query_builder.rs
  hermes/apps/athena/modules/rbac-registration/src/database/select/cat_id.rs
  hermes/apps/athena/modules/rbac-registration/src/database/select/mod.rs
  hermes/apps/athena/modules/rbac-registration/src/database/select/stake_addr.rs
  hermes/apps/athena/modules/rbac-registration/src/database/statement.rs
  hermes/apps/athena/modules/rbac-registration/src/lib.rs
  hermes/apps/athena/modules/rbac-registration/src/rbac/build_rbac_chain.rs
  hermes/apps/athena/modules/rbac-registration/src/rbac/get_rbac.rs
  hermes/apps/athena/modules/rbac-registration/src/rbac/mod.rs
  hermes/apps/athena/modules/rbac-registration/src/utils/cardano/block.rs
  hermes/apps/athena/modules/rbac-registration/src/utils/cardano/mod.rs
  hermes/apps/athena/modules/rbac-registration/src/utils/log.rs
  hermes/apps/athena/modules/rbac-registration/src/utils/mod.rs
  hermes/apps/athena/modules/rbac-registration/src/utils/value.rs
  justfile
Labels: review me, squad: hermetics
