Repository input-output-hk/hermes, pull requests merged in 2025-07, with the labels that each got.

#426 feat(general): add ci jobs to sync labels
  .github/workflows/sync-labels.yml
Labels: review me

#441 feat(hermes): Add svg validation
  .config/dictionaries/project.dic
  hermes/bin/Cargo.toml
  hermes/bin/src/packaging/app/mod.rs
  hermes/bin/src/packaging/app/tests.rs
Labels: review me, squad: hermetics

#438 fix(hermes): Modify the Cardano integration test.
  hermes/Earthfile
  wasm/integration-test/cardano/src/lib.rs
  wasm/integration-test/clocks/clocks.c
  wasm/integration-test/cron/cron.c
  wasm/integration-test/crypto/crypto.c
  wasm/integration-test/hashing/hashing.c
  wasm/integration-test/http_reply/src/lib.rs
  wasm/integration-test/ipfs/src/lib.rs
  wasm/integration-test/localtime/localtime.c
  wasm/integration-test/logger/logger.c
  wasm/integration-test/smoke-test/smoke-test.c
  wasm/integration-test/sqlite/src/lib.rs
  wasm/integration-test/wasi-filesystem/src/lib.rs
  wasm/stub-module/stub-module.c
Labels: review me, squad: hermetics

#436 fix(hermes): New Cardano runtime implementation
  hermes/Earthfile
  hermes/bin/Cargo.toml
  hermes/bin/src/runtime_extensions/hermes/cardano/block.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/chain_follower_task.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/event.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/host.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/mod.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/network.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/tokio_runtime_task.rs
  hermes/bin/src/runtime_extensions/hermes/crypto/bip32_ed25519.rs
  hermes/bin/src/runtime_extensions/mod.rs
  hermes/bin/src/runtime_extensions/resource_manager.rs
  hermes/bin/src/runtime_extensions/utils/conversion.rs
  hermes/bin/src/runtime_extensions/utils/mod.rs
  wasm/integration-test/cardano/src/lib.rs
  wasm/integration-test/clocks/clocks.c
  wasm/integration-test/cron/cron.c
  wasm/integration-test/crypto/crypto.c
  wasm/integration-test/hashing/hashing.c
  wasm/integration-test/http_reply/src/lib.rs
  wasm/integration-test/ipfs/src/lib.rs
  wasm/integration-test/localtime/localtime.c
  wasm/integration-test/logger/logger.c
  wasm/integration-test/smoke-test/smoke-test.c
  wasm/integration-test/sqlite/src/lib.rs
  wasm/integration-test/wasi-filesystem/src/lib.rs
  wasm/stub-module/stub-module.c
Labels: squad: hermetics

#425 fix(wasm): Update Cardano Chain Follower WIT interface
  hermes/Earthfile
  hermes/bin/Cargo.toml
  hermes/bin/src/runtime_extensions/hermes/cardano/block.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/chain_follower_task.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/event.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/host.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/mod.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/network.rs
  hermes/bin/src/runtime_extensions/hermes/cardano/tokio_runtime_task.rs
  hermes/bin/src/runtime_extensions/hermes/crypto/bip32_ed25519.rs
  hermes/bin/src/runtime_extensions/mod.rs
  hermes/bin/src/runtime_extensions/resource_manager.rs
  hermes/bin/src/runtime_extensions/utils/conversion.rs
  hermes/bin/src/runtime_extensions/utils/mod.rs
  wasm/integration-test/cardano/src/lib.rs
  wasm/integration-test/clocks/clocks.c
  wasm/integration-test/cron/cron.c
  wasm/integration-test/crypto/crypto.c
  wasm/integration-test/hashing/hashing.c
  wasm/integration-test/http_reply/src/lib.rs
  wasm/integration-test/ipfs/src/lib.rs
  wasm/integration-test/localtime/localtime.c
  wasm/integration-test/logger/logger.c
  wasm/integration-test/smoke-test/smoke-test.c
  wasm/integration-test/sqlite/src/lib.rs
  wasm/integration-test/wasi-filesystem/src/lib.rs
  wasm/stub-module/stub-module.c
  wasm/wasi/wit/deps/hermes-cardano/api.wit
  wasm/wasi/wit/deps/hermes-cardano/event.wit
  wasm/wasi/wit/deps/hermes-cardano/world.wit
  wasm/wasi/wit/deps/hermes-hash/api.wit
Labels: do not merge yet, squad: hermetics, requires architect review
